# Generated by Django 3.2 on 2022-02-17 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0002_auto_20220212_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
    ]
