# Generated by Django 3.2 on 2022-02-19 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0003_alter_publication_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='poster',
            field=models.ImageField(null=True, upload_to='publication_images', verbose_name='Постер'),
        ),
    ]
